### ISSUE TITLE
Weird URL format

### ISSUE THREAD

**Issue by neeraj-reddy** [JacintoDesign/bookmark-app#1]
When a bookmark is added with full URL, it adds `https//` in between the protocol and domain.

For instance, when `https://www.google.com` is added through the form, it stores `https://https//www.google.com`.

![screenshot](https://user-images.githubusercontent.com/34216876/99187610-a2c2c200-277d-11eb-941a-a57e680aef57.png)

**Comment by JacintoDesign** [comment]
You're right, good attention to detail, I need the syntax to be different because an .includes method can only take one parameter. The revised code has been pushed to the master branch and I've updated the final zip file on Udemy/Google Drive.
